# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'PullToRefreshKit'
  pod 'PopupDialog'
  pod 'SwiftyJSON'
  pod 'lottie-ios'
  pod 'TouchDraw'


  # Pods for PDFCreator

end
